### ISSUE TITLE
doesn't work out of the box

### ISSUE THREAD

**Issue by semiessessi** [blackrosezy/build-libcurl-windows#1]
a little investigation reveals a load of undocumented dependencies (or i missed this in the documentation)

set ROOT_DIR="%CD%"
set RM="%CD%\bin\unxutils\rm.exe"
set CP="%CD%\bin\unxutils\cp.exe"
set MKDIR="%CD%\bin\unxutils\mkdir.exe"
set SEVEN_ZIP="%CD%\bin\7-zip\7za.exe"
set WGET="%CD%\bin\unxutils\wget.exe"
set XIDEL="%CD%\bin\xidel\xidel.exe"

it should be documented that there are a bunch of dependencies.

**Comment by blackrosezy** [comment]
Readme file has been updated.
