### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by bionyxxx** [blackrosezy/build-libcurl-windows#23]
Hello,
I have a problem that keeps me stuck while building libcurl on my windows 10.  I'm using visual studio 2015 and I've tried many times but the result is just the same as not working.
I am here to ask for help, thank you

> link.exe /incremental:no /libpath:"..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel\lib" /out:..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel\bin\curl.exe /subsystem:console /nologo /machine:x64 libcurl_a.lib ws2_32.lib wldap32.lib advapi32.lib crypt32.lib Normaliz.lib Crypt32.lib ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\tool_hugehelp.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\nonblock.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\strtoofft.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\warnless.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\curl_ctype.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\curl_multibyte.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\version_win32.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\dynbuf.obj ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/slist_wc.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_binmode.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_bname.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cb_dbg.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cb_hdr.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cb_prg.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cb_rea.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cb_see.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cb_wrt.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_cfgable.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_convert.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_dirhie.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_doswin.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_easysrc.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_filetime.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_formparse.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_getparam.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_getpass.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_help.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_helpers.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_homedir.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_libinfo.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_main.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_metalink.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_msgs.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_operate.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_operhlp.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_panykey.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_paramhlp.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_parsecfg.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_progress.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_strdup.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_setopt.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_sleep.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_urlglob.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_util.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_vms.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_writeout.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_writeout_json.obj  ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl/tool_xattr.obj   ..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-curl\curl.res
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.pdb: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: bin\*.dll: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.pdb: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: bin\*.dll: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.pdb: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: bin\*.dll: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.pdb: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: bin\*.dll: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
The system cannot find the path specified.
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: lib\*.lib: No such file or directory
C:\build-libcurl-windows-master\bin\unxutils\cp.exe: include: No such file or directory
Done.

**Comment by 0xcircuitbreaker** [comment]
I am having the same issue, did you find a solution?

**Comment by sclaggett** [comment]
Something seems to have changed recently in the libcurl source and the build directories are no longer what they once were.

Workaround: Open a Git Bash terminal and run `sed -i 's/winssl/schannel/g' build.bat` prior to running `build.bat` in a Developer Command Prompt terminal. To save yourself some time, you may want to try running `rc` in the terminal before the batch file. Use [this](https://stackoverflow.com/questions/43847542/rc-exe-no-longer-found-in-vs-2015-command-prompt) workaround if it isn't found.

Thanks to blackrosezy for this script. Coming from Mac/Linux, I'm frankly appalled how difficult it has been to get my hands on a Windows build of libcurl. I feel like there must be an easy solution that I'm missing.
