### ISSUE TITLE
appveyor says that build is passing, while it's full of errors

### ISSUE THREAD

**Issue by justanotheranonymoususer** [blackrosezy/build-libcurl-windows#8]
For example:
https://ci.appveyor.com/project/blackrosezy/build-libcurl-windows-unln0/build/1.0.153

Perhaps the batch should check for errors, and exit with an error code if any error occurs.

**Comment by darki73** [comment]
Because it just wasnt able to download curl zip package. As you can see, its downloaded text/html for some reason

**Comment by justanotheranonymoususer** [comment]
Yeah, this is the reason:
https://github.com/blackrosezy/build-libcurl-windows/pull/7

This failure should be detected, and the test shouldn't pass

**Comment by blackrosezy** [comment]
The problem has been fixed.
